spring:
  application:
    name: TaskManagerSpring

  datasource:
    url: jdbc:postgresql://localhost:54321/taskmanager
    username: ${taskmanager}
    password: ${123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true